import { AppState } from "./types";

export const initialKategoriIntrakurikuler = [
  { id: "KAT-01", namaKategori: "Nilai Agama dan Budi Pekerti" },
  { id: "KAT-02", namaKategori: "Jati Diri" },
  { id: "KAT-03", namaKategori: "Dasar-Dasar Literasi, Matematika, Sains, Teknologi, Rekayasa, dan Seni" },
];

export const seedData: AppState = {
  kelas: [
    { id: "K-01", namaKelas: "Kelas Pelangi (A - Usia 4-5 Tahun)", waliKelas: "Ibu Rahma Nuraini, S.Pd.", nuptkNgty: "2034765892110032" },
    { id: "K-02", namaKelas: "Kelas Bintang (B - Usia 5-6 Tahun)", waliKelas: "Ibu Sri Wahyuni, S.Pd.", nuptkNgty: "1045876329000122" },
  ],
  siswa: [
    {
      id: "S-01",
      namaSiswa: "Ahmad Aditya Pratama",
      nisn: "3301020405180001",
      alamat: "Jl. Merpati No. 12, Gajahmungkur, Semarang",
      namaAyah: "Budi Pratama",
      pekerjaanAyah: "Wiraswasta",
      namaIbu: "Sari Pertiwi",
      pekerjaanIbu: "Ibu Rumah Tangga",
      noHp: "081234567890",
      tglLahir: "2018-05-04",
      tempatLahir: "Semarang",
      jenisKelamin: "Laki-laki",
      anakKe: 1,
      tb: "105",
      bb: "16",
      agama: "Islam",
      idKelas: "K-02",
    },
    {
      id: "S-02",
      namaSiswa: "Aisyah Az-Zahra",
      nisn: "3301021208180002",
      alamat: "Perum Graha Indah Blok C/3, Tembalang, Semarang",
      namaAyah: "Ahmad Baihaqi",
      pekerjaanAyah: "PNS",
      namaIbu: "Fatimah Zahra",
      pekerjaanIbu: "Guru",
      noHp: "082345678901",
      tglLahir: "2018-08-12",
      tempatLahir: "Demak",
      jenisKelamin: "Perempuan",
      anakKe: 2,
      tb: "102",
      bb: "15",
      agama: "Islam",
      idKelas: "K-02",
    },
    {
      id: "S-03",
      namaSiswa: "Bagus Setiawan",
      nisn: "3301022010180003",
      alamat: "Kp. Krajan RT 02/RW 01, Semarang",
      namaAyah: "Rudi Setiawan",
      pekerjaanAyah: "Karyawan Swasta",
      namaIbu: "Endang W",
      pekerjaanIbu: "Wiraswasta",
      noHp: "085672349012",
      tglLahir: "2018-10-20",
      tempatLahir: "Semarang",
      jenisKelamin: "Laki-laki",
      anakKe: 1,
      tb: "108",
      bb: "17.5",
      agama: "Kristen",
      idKelas: "K-02",
    },
    {
      id: "S-04",
      namaSiswa: "Callysta Aurelia",
      nisn: "3301031502190001",
      alamat: "Jl. Pemuda No. 45, Pandanaran, Semarang",
      namaAyah: "Hendra Wijaya",
      pekerjaanAyah: "Wiraswasta",
      namaIbu: "Sisil",
      pekerjaanIbu: "Ibu Rumah Tangga",
      noHp: "081987654321",
      tglLahir: "2019-02-15",
      tempatLahir: "Semarang",
      jenisKelamin: "Perempuan",
      anakKe: 3,
      tb: "98",
      bb: "14",
      agama: "Katolik",
      idKelas: "K-01",
    },
    {
      id: "S-05",
      namaSiswa: "Daffa Al-Fatih",
      nisn: "3301032506190002",
      alamat: "Dusun Krajan Lor RT 01/RW 03, Semarang",
      namaAyah: "Irfan Al-Fatih",
      pekerjaanAyah: "Tani",
      namaIbu: "Siti Masitoh",
      pekerjaanIbu: "Ibu Rumah Tangga",
      noHp: "081299887766",
      tglLahir: "2019-06-25",
      tempatLahir: "Mijen",
      jenisKelamin: "Laki-laki",
      anakKe: 1,
      tb: "100",
      bb: "14.5",
      agama: "Islam",
      idKelas: "K-01",
    },
  ],
  kategoriIntrakurikuler: initialKategoriIntrakurikuler,
  tujuanPembelajaran: [
    // Kelas B (K-02)
    { id: "TP-01", idKategori: "KAT-01", deskripsi: "Mengenal Tuhan Yang Maha Esa dan terbiasa melaksanakan ibadah harian sesuai agamanya.", idKelas: "K-02" },
    { id: "TP-02", idKategori: "KAT-01", deskripsi: "Menunjukkan sikap budi pekerti santun, jujur, penolong, dan menghargai ciptaan Tuhan.", idKelas: "K-02" },
    { id: "TP-03", idKategori: "KAT-02", deskripsi: "Menunjukkan perilaku positif prososial (bersosialisasi, tertib mengantre, dan menolong teman).", idKelas: "K-02" },
    { id: "TP-04", idKategori: "KAT-02", deskripsi: "Berpartisipasi aktif dalam gerakan kinetik kasar dan halus untuk kesehatan fisik anak.", idKelas: "K-02" },
    { id: "TP-05", idKategori: "KAT-03", deskripsi: "Mengenali kosakata, membaca simbol/huruf, dan mengekspresikan pikiran secara lisan.", idKelas: "K-02" },
    { id: "TP-06", idKategori: "KAT-03", deskripsi: "Mengenal hubungan kuantitas bilangan, bentuk geometri, dan membandingkan klasifikasi objek.", idKelas: "K-02" },

    // Kelas A (K-01)
    { id: "TP-07", idKategori: "KAT-01", deskripsi: "Mulai menirukan gerakan ibadah bermakna sesuai tuntunan agama orang tua.", idKelas: "K-01" },
    { id: "TP-08", idKategori: "KAT-01", deskripsi: "Terbiasa mengucapkan kalimat santun seperti Tolong, Terima Kasih, dan Maaf.", idKelas: "K-01" },
    { id: "TP-09", idKategori: "KAT-02", deskripsi: "Belajar mengenali emosi pribadi dan mengenali kebutuhan fisik mandiri.", idKelas: "K-01" },
    { id: "TP-10", idKategori: "KAT-03", deskripsi: "Mendengarkan instruksi guru dengan baik dan mencoba mengeksplorasi coretan/gambar bebas.", idKelas: "K-01" },
  ],
  subdimensiKokurikuler: [
    // Kelas B
    { id: "KO-01", namaSubdimensi: "Dimensi Beriman, Bertakwa Kepada Tuhan YME (Akhlak mulia dan adab sesama)", idKelas: "K-02" },
    { id: "KO-02", namaSubdimensi: "Dimensi Gotong Royong (Berbagi peran dan kerjasama menyelesaikan tugas kelompok P5)", idKelas: "K-02" },
    { id: "KO-03", namaSubdimensi: "Dimensi Mandiri (Berusaha menyelesaikan karyanya sendiri dengan percaya diri)", idKelas: "K-02" },

    // Kelas A
    { id: "KO-04", namaSubdimensi: "Dimensi Gotong Royong (Belajar berbagi alat permainan bersama)", idKelas: "K-01" },
    { id: "KO-05", namaSubdimensi: "Dimensi Kreatif (Mencoba menyusun balok atau mencampur warna baru)", idKelas: "K-01" },
  ],
  labelP5: [
    { id: "L-01", namaLabel: "Berkembang", order: 1 },
    { id: "L-02", namaLabel: "Cakap", order: 2 },
    { id: "L-03", namaLabel: "Mahir", order: 3 },
  ],
  nilaiIntrakurikuler: [
    // Aditya (S-01)
    { idSiswa: "S-01", idTp: "TP-01", nilai: "Mahir" },
    { idSiswa: "S-01", idTp: "TP-02", nilai: "Cakap" },
    { idSiswa: "S-01", idTp: "TP-03", nilai: "Cakap" },
    { idSiswa: "S-01", idTp: "TP-04", nilai: "Mahir" },
    { idSiswa: "S-01", idTp: "TP-05", nilai: "Berkembang" },
    { idSiswa: "S-01", idTp: "TP-06", nilai: "Cakap" },

    // Aisyah (S-02)
    { idSiswa: "S-02", idTp: "TP-01", nilai: "Mahir" },
    { idSiswa: "S-02", idTp: "TP-02", nilai: "Mahir" },
    { idSiswa: "S-02", idTp: "TP-03", nilai: "Mahir" },
    { idSiswa: "S-02", idTp: "TP-04", nilai: "Cakap" },
    { idSiswa: "S-02", idTp: "TP-05", nilai: "Mahir" },
    { idSiswa: "S-02", idTp: "TP-06", nilai: "Cakap" },
  ],
  nilaiKokurikuler: [
    { idSiswa: "S-01", idSubdimensi: "KO-01", nilai: "Mahir" },
    { idSiswa: "S-01", idSubdimensi: "KO-02", nilai: "Cakap" },
    { idSiswa: "S-01", idSubdimensi: "KO-03", nilai: "Cakap" },

    { idSiswa: "S-02", idSubdimensi: "KO-01", nilai: "Mahir" },
    { idSiswa: "S-02", idSubdimensi: "KO-02", nilai: "Mahir" },
    { idSiswa: "S-02", idSubdimensi: "KO-03", nilai: "Cakap" },
  ],
  catatanAnak: [
    {
      idSiswa: "S-01",
      catatan: "Ananda Aditya menunjukkan perkembangan yang luar biasa baik pada aspek spritual dan fisik motorik. Ia secara antusias memimpin doa doa harian di hadapan teman-temannya di kelas. Pada ranah motorik, Aditya sangat tangkas melempar bola dan menyeimbangkan badannya. Perlu bimbingan lebih intensif dalam mengenali bunyi huruf abjad dasar melalui media belajar visual yang menarik di rumah agar minat membaca berkembang pesat.",
    },
    {
      idSiswa: "S-02",
      catatan: "Ananda Aisyah adalah pribadi yang ceria, penuh rasa ingin tahu, dan sangat santun. Kemampuan literasi Aisyah berkembang pesat; ia sudah mengenali sebagian besar abjad dan merangkai kata pendek. Dalam projek P5 bertema gaya hidup berkelanjutan, Aisyah sangat bersemangat membantu mengumpulkan sampah botol plastik bekas untuk dijadikan vas tanaman kelompoknya.",
    },
  ],
  kehadiran: [
    { idSiswa: "S-01", sakit: 1, ijin: 2, tanpaKet: 0 },
    { idSiswa: "S-02", sakit: 0, ijin: 1, tanpaKet: 0 },
    { idSiswa: "S-03", sakit: 3, ijin: 0, tanpaKet: 1 },
    { idSiswa: "S-04", sakit: 0, ijin: 0, tanpaKet: 0 },
    { idSiswa: "S-05", sakit: 2, ijin: 1, tanpaKet: 0 },
  ],
  dataSekolah: {
    namaSekolah: "PAUD & TK Bunga Bangsa Mijen",
    alamat: "Jl. Diponegoro RT 02/RW 04, Mijen, Kec. Mijen, Kota Semarang, Jawa Tengah",
    kepalaSekolah: "Hj. Endang Sulastri, S.Pd.Aud.",
    logo: "", // default custom avatar
    semester: "2 (Genap)",
    thAjaran: "2025/2026",
    tglRaport: "2026-06-20",
    npsn: "69835194",
  },
};
